services:
  # Nuxt.js 前台
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: firestar-temporary--docker-frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - .nuxt:/app/.nuxt
    ports:
      - "${FRONTEND_PORT:-8010}:8010"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      NUXT_PUBLIC_API_BASE: ${NUXT_PUBLIC_API_BASE:-http://localhost:8082}
      HOST: 0.0.0.0
      PORT: 8010
      CI: "true"
    develop:
      watch:
        # sync static content
        - path: ./app
          action: sync
          target: /app
          ignore:
            - node_modules/


volumes:
  node_modules:
    driver: local
  .nuxt:
    driver: local
